# Substitua "SEU_USUARIO" pelo seu usuário do GitHub/SonarCloud
sonar.projectKey=agrobanana
sonar.organization=SEU_USUARIO
sonar.projectName=AgroBanana
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

sonar.exclusions=app/migrations/**,app/extensions.py
sonar.coverage.exclusions=app/migrations/**,app/__init__.py,app/extensions.py
