"""peso_por_caixa e reset senha

Revision ID: 95a2373bad69
Revises: a5fa3a4da49a
Create Date: 2026-06-11 22:32:15.940961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a2373bad69'
down_revision = 'a5fa3a4da49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colheitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_por_caixa', sa.Float(), nullable=True))
        batch_op.drop_column('peso_kg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colheitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_kg', sa.FLOAT(), nullable=True))
        batch_op.drop_column('peso_por_caixa')

    # ### end Alembic commands ###
